apiVerion: skaffold/v2apha3
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"
build:
  local:
    push: false
  arifacts:
    - image: taylone/clinet
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: taylone/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: taylone/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: taylone/event-bus
      context: event-bus
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: taylone/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: taylone/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
